resume: false
device: GPU
epochs: 200
batch_size: 16
weights: /home/ma-user/work/MindSpore/model/weights/yolov5s_datav3_1024.ckpt
data: ./train_utils/speedstar.yaml
hyp: ./train_utils/hyp.speedstar.yaml
cfg: ''
img_size:
- 1024
- 1024
workers: 4
rect: false
nosave: false
noval: false
noautoanchor: false
cache_images: false
image_weights: false
multi_scale: false
adam: false
sync_bn: false
exist_ok: true
linear_lr: false
label_smoothing: 0.0
save_period: -1
artifact_alias: latest
save_dir: run
multi_process: true
